# Generated by Django 3.2.15 on 2022-09-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed'), ('Merged', 'Merged')], max_length=250)),
                ('creation_date', models.DateField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protosure_issue_tracker.repositoryinfo')),
            ],
        ),
    ]
