# Generated by Django 3.2.15 on 2022-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issuemetadata',
            name='title_status_IssueMetadata_should_not_close_check',
        ),
        migrations.AddConstraint(
            model_name='issuemetadata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('title__contains', 'WIP'), _negated=True), models.Q(models.Q(('title__contains', 'DRAFT'), _negated=True), ('status__in', ['Draft', 'Open', 'Merged'])), _connector='OR'), name='title_status_IssueMetadata_should_not_close_check'),
        ),
    ]
