# Generated by Django 3.2.15 on 2022-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0002_auto_20220919_1035'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issuemetadata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('title__contains', 'DRAFT'), _negated=True), models.Q(models.Q(('title__contains', 'WIP'), _negated=True), ('status__in', ['Draft', 'Open', 'Merged'])), _connector='OR'), name='DRAFT_should_not_be_close'),
        ),
    ]
