# Generated by Django 3.2.15 on 2022-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0003_issuemetadata_draft_should_not_be_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemetadata',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
