# Generated by Django 3.2.15 on 2022-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0003_auto_20220917_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomments',
            name='comment_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
