# Generated by Django 3.2.15 on 2022-09-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0005_alter_issuecomments_issue'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issuemetadata',
            constraint=models.UniqueConstraint(condition=models.Q(('title__contains', 'WIP'), models.Q(('title__contains', 'DRAFT'), models.Q(('status', 'Closed'), _negated=True)), _connector='OR'), fields=('title', 'status'), name='title_status_IssueMetadata_should_not_close'),
        ),
    ]
