# Generated by Django 3.2.15 on 2022-09-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0006_issuemetadata_title_status_issuemetadata_should_not_close'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issuemetadata',
            name='title_status_IssueMetadata_should_not_close',
        ),
        migrations.AddConstraint(
            model_name='issuemetadata',
            constraint=models.UniqueConstraint(condition=models.Q(('title__contains', 'WIP'), models.Q(('title__contains', 'DRAFT'), ('status', 'Closed')), _connector='OR'), fields=('title', 'status'), name='title_status_IssueMetadata_should_not_close'),
        ),
    ]
