# Generated by Django 3.2.15 on 2022-09-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0007_auto_20220919_0057'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issuemetadata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('title__contains', 'WIP'), _negated=True), models.Q(models.Q(('title__contains', 'DRAFT'), _negated=True), models.Q(('status', 'Closed'), _negated=True)), _connector='OR'), name='title_status_IssueMetadata_should_not_close_check'),
        ),
    ]
