# Generated by Django 3.2.15 on 2022-09-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protosure_issue_tracker', '0008_issuemetadata_title_status_issuemetadata_should_not_close_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issuemetadata',
            name='title_status_IssueMetadata_should_not_close',
        ),
    ]
